### ISSUE TITLE
TypeError when importing gmxapi 0.0.8

### ISSUE THREAD

**Issue by sperezconesa** [kassonlab/gmxapi#267]
Hello,

When trying to import gmxapi==0.0.8 using python==3.8.5 or 3.7.9 . I get the following error.

```python
>>> import gmxapi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nethome/sperez/bin/anaconda3/envs/string_method2/lib/python3.8/site-packages/gmxapi/__init__.py", line 64, in <module>
    from .operation import computed_result, function_wrapper
  File "/nethome/sperez/bin/anaconda3/envs/string_method2/lib/python3.8/site-packages/gmxapi/operation.py", line 1037, in <module>
    class OperationRegistry(typing.Mapping[OperationRegistryKey, OperationImplementation], collections.UserDict):
  File "/nethome/sperez/bin/anaconda3/envs/string_method2/lib/python3.8/abc.py", line 85, in __new__
    cls = super().__new__(mcls, name, bases, namespace, **kwargs)
TypeError: Cannot create a consistent method resolution
order (MRO) for bases Mapping, Generic, UserDict
```
I am not sure what could be causing this... I leave my anaconda directory specifications below in case it is usefull.

Let me know if there is anything else I can do!
Best,
Sergio
```bash
# packages in environment at /nethome/sperez/bin/anaconda3/envs/string_method2:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
anyio                     2.1.0            py37h89c1867_0    conda-forge
argon2-cffi               20.1.0           py37h5e8e339_2    conda-forge
async_generator           1.10                       py_0    conda-forge
attrs                     20.3.0             pyhd3deb0d_0    conda-forge
babel                     2.9.0              pyhd3deb0d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
biopython                 1.78             py37h5e8e339_1    conda-forge
bleach                    3.3.0              pyh44b312d_0    conda-forge
brotlipy                  0.7.0           py37h5e8e339_1001    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.17.1               h36c2ea0_0    conda-forge
ca-certificates           2020.12.5            ha878542_0    conda-forge
certifi                   2020.12.5        py37h89c1867_1    conda-forge
cffi                      1.14.5           py37hc58025e_0    conda-forge
cftime                    1.4.1            py37h902c9e0_0    conda-forge
chardet                   4.0.0            py37h89c1867_1    conda-forge
cryptography              3.4.4            py37hf1a17b8_0    conda-forge
curl                      7.71.1               he644dc0_8    conda-forge
cycler                    0.10.0                     py_2    conda-forge
dbus                      1.13.6               hfdff14a_1    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
expat                     2.2.10               h9c3ff4c_0    conda-forge
fontconfig                2.13.1            hba837de_1004    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
gettext                   0.19.8.1          h0b5b191_1005    conda-forge
glib                      2.66.7               h9c3ff4c_0    conda-forge
glib-tools                2.66.7               h9c3ff4c_0    conda-forge
gmxapi                    0.0.8                    pypi_0    pypi
griddataformats           0.5.0                      py_0    conda-forge
gsd                       2.4.0            py37h902c9e0_0    conda-forge
gst-plugins-base          1.14.5               h0935bb2_2    conda-forge
gstreamer                 1.18.3               h3560a44_0    conda-forge
hdf4                      4.2.13            h10796ff_1004    conda-forge
hdf5                      1.10.6          nompi_h6a2412b_1114    conda-forge
icu                       68.1                 h58526e2_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
importlib-metadata        3.4.0            py37h89c1867_0    conda-forge
importlib_metadata        3.4.0                hd8ed1ab_0    conda-forge
ipykernel                 5.4.2            py37h888b3d9_0    conda-forge
ipython                   7.20.0           py37h888b3d9_2    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.18.0           py37h89c1867_2    conda-forge
jinja2                    2.11.3             pyh44b312d_0    conda-forge
joblib                    1.0.1              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   h36c2ea0_0    conda-forge
json5                     0.9.5              pyh9f0ad1d_0    conda-forge
jsonschema                3.2.0                      py_2    conda-forge
jupyter_client            6.1.11             pyhd8ed1ab_1    conda-forge
jupyter_core              4.7.1            py37h89c1867_0    conda-forge
jupyter_server            1.3.0            py37h89c1867_0    conda-forge
jupyterlab                3.0.8              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_server         2.2.1              pyhd8ed1ab_0    conda-forge
kiwisolver                1.3.1            py37h2527ec5_1    conda-forge
krb5                      1.17.2               h926e7f8_0    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.35.1               hea4e1c9_2    conda-forge
libblas                   3.9.0                8_openblas    conda-forge
libcblas                  3.9.0                8_openblas    conda-forge
libclang                  11.0.1          default_ha53f305_1    conda-forge
libcurl                   7.71.1               hcdd3856_8    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.10               hcdb4288_3    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 9.3.0               h2828fa1_18    conda-forge
libgfortran-ng            9.3.0               hff62375_18    conda-forge
libgfortran5              9.3.0               hff62375_18    conda-forge
libglib                   2.66.7               h1f3bc88_0    conda-forge
libgomp                   9.3.0               h2828fa1_18    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0                8_openblas    conda-forge
libllvm11                 11.0.1               hf817b99_0    conda-forge
libnetcdf                 4.7.4           nompi_h56d31a8_107    conda-forge
libnghttp2                1.43.0               h812cca2_0    conda-forge
libopenblas               0.3.12          pthreads_h4812303_1    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libpq                     12.3                 h255efa7_3    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libssh2                   1.9.0                hab1572f_5    conda-forge
libstdcxx-ng              9.3.0               h6de172a_18    conda-forge
libtiff                   4.2.0                hdc55705_0    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libwebp-base              1.2.0                h7f98852_0    conda-forge
libxcb                    1.13              h7f98852_1003    conda-forge
libxkbcommon              1.0.3                he3ba5ed_0    conda-forge
libxml2                   2.9.10               h72842e0_3    conda-forge
lz4-c                     1.9.3                h9c3ff4c_0    conda-forge
markupsafe                1.1.1            py37h5e8e339_3    conda-forge
matplotlib                3.3.4            py37h89c1867_0    conda-forge
matplotlib-base           3.3.4            py37h0c9df89_0    conda-forge
mdanalysis                1.0.0            py37hcd2ae1e_2    conda-forge
mistune                   0.8.4           py37h5e8e339_1003    conda-forge
mmtf-python               1.1.2                      py_0    conda-forge
mpi                       1.0                     openmpi    conda-forge
mpi4py                    3.0.3            py37h3e1c8c0_5    conda-forge
msgpack-python            1.0.2            py37h2527ec5_1    conda-forge
mysql-common              8.0.22               ha770c72_3    conda-forge
mysql-libs                8.0.22               h935591d_3    conda-forge
nbclassic                 0.2.6              pyhd8ed1ab_0    conda-forge
nbclient                  0.5.2              pyhd8ed1ab_0    conda-forge
nbconvert                 6.0.7            py37h89c1867_3    conda-forge
nbformat                  5.1.2              pyhd8ed1ab_1    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
nest-asyncio              1.4.3              pyhd8ed1ab_0    conda-forge
netcdf4                   1.5.6           nompi_py37hdbee05a_100    conda-forge
networkx                  2.5                        py_0    conda-forge
notebook                  6.2.0            py37h89c1867_0    conda-forge
nspr                      4.29                 h9c3ff4c_1    conda-forge
nss                       3.61                 hb5efdd6_0    conda-forge
numpy                     1.20.1           py37haa41c4c_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openmpi                   4.1.0                h9b22176_1    conda-forge
openssl                   1.1.1j               h7f98852_0    conda-forge
packaging                 20.9               pyh44b312d_0    conda-forge
pandas                    1.2.2            py37hdc94413_0    conda-forge
pandoc                    2.11.4               h7f98852_0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.8.1              pyhd8ed1ab_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.1.0            py37h4600e1f_2    conda-forge
pip                       21.0.1             pyhd8ed1ab_0    conda-forge
prometheus_client         0.9.0              pyhd3deb0d_0    conda-forge
prompt-toolkit            3.0.16             pyha770c72_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygments                  2.8.0              pyhd8ed1ab_0    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.12.3           py37h89c1867_7    conda-forge
pyqt-impl                 5.12.3           py37he336c9b_7    conda-forge
pyqt5-sip                 4.19.18          py37hcd2ae1e_7    conda-forge
pyqtchart                 5.12             py37he336c9b_7    conda-forge
pyqtwebengine             5.12.1           py37he336c9b_7    conda-forge
pyrsistent                0.17.3           py37h5e8e339_2    conda-forge
pysocks                   1.7.1            py37h89c1867_3    conda-forge
python                    3.7.9           hffdb5ce_100_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
pyzmq                     22.0.3           py37h499b945_0    conda-forge
qt                        5.12.9               h9d6b050_2    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
requests                  2.25.1             pyhd3deb0d_0    conda-forge
scikit-learn              0.24.1           py37h69acf81_0    conda-forge
scipy                     1.6.0            py37h14a347d_0    conda-forge
seaborn                   0.11.1               hd8ed1ab_1    conda-forge
seaborn-base              0.11.1             pyhd8ed1ab_1    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                49.6.0           py37h89c1867_3    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sniffio                   1.2.0            py37h89c1867_1    conda-forge
sqlite                    3.34.0               h74cdb3f_0    conda-forge
statsmodels               0.12.2           py37h902c9e0_0    conda-forge
terminado                 0.9.2            py37h89c1867_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
tk                        8.6.10               h21135ba_1    conda-forge
tornado                   6.1              py37h5e8e339_1    conda-forge
tqdm                      4.57.0             pyhd8ed1ab_0    conda-forge
traitlets                 5.0.5                      py_0    conda-forge
typing_extensions         3.7.4.3                    py_0    conda-forge
urllib3                   1.26.3             pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zeromq                    4.3.4                h9c3ff4c_0    conda-forge
zipp                      3.4.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.4.8                ha95c52a_1    conda-forge
```

**Comment by eirrgang** [comment]
Interesting! I guess I haven't updated that branch of gmxapi since Python 3.7! :-)

The issue is the result of me failing to account for an undocumented change in `typing.Generic` with 3.7 (which has since been corrected). I didn't realize I overlooked it in the older gmxapi branches, though. Basically, some of the classes need their base classes adjusted.

Can you tell me how you installed gmxapi 0.0.8? It looks like you just did a `pip install gmxapi==0.0.8` to get it from PyPI? Or did you clone one of the `git` repositories? I just want to make sure that I fix it in all of the right places.

**Comment by sperezconesa** [comment]
I actually only did: `pip install gmxapi`

**Comment by sperezconesa** [comment]
Thanks for the rapid response!

**Comment by eirrgang** [comment]
> I actually only did: `pip install gmxapi`

You didn't specify the gmxapi version? That's strange... What version of GROMACS are you using? What happens if you try to install a more recent version of gmxapi? Can you try the following?

If you are using GROMACS 2020: `pip install --upgrade "gmxapi==0.1.0.1"`

If you are using GROMACS 2021: `pip install --upgrade "gmxapi>=0.2"`

**Comment by sperezconesa** [comment]
I'm using gmx2020:
If I do `pip install --upgrade "gmxapi==0.1.0.1"`:
I get:
```bash
Collecting gmxapi==0.1.0.1
  Using cached gmxapi-0.1.0.1.tar.gz (284 kB)
    ERROR: Command errored out with exit status 1:
     command: /nethome/sperez/bin/anaconda3/envs/string_method3/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-587r0dm4/gmxapi_79d72a8deab644a28dc7d01fea6187e6/setup.py'"'"'; __file__='"'"'/tmp/pip-install-587r0dm4/gmxapi_79d72a8deab644a28dc7d01fea6187e6/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-zhe7pf24
         cwd: /tmp/pip-install-587r0dm4/gmxapi_79d72a8deab644a28dc7d01fea6187e6/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-587r0dm4/gmxapi_79d72a8deab644a28dc7d01fea6187e6/setup.py", line 53, in <module>
        from skbuild import setup
    ModuleNotFoundError: No module named 'skbuild'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/6e/c7/ad26d9706474e43ef1a7589397cc2080cebd9deca48efdaaee956c43d8b7/gmxapi-0.1.0.1.tar.gz#sha256=3371075975117a32ffe44e8972a4a9330da416f0054e00ee587cdffb217497a0 (from https://pypi.org/simple/gmxapi/) (requires-python:>=3.5, <3.9). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement gmxapi==0.1.0.1
ERROR: No matching distribution found for gmxapi==0.1.0.1
```
I am not sure what this means. I am working on our local linux-cluster if that is any help.

**Comment by sperezconesa** [comment]
If I'm missing skbuild, why isn't it installing it?

**Comment by eirrgang** [comment]
> If I'm missing skbuild, why isn't it installing it?

Sorry about that. A logic error, I'm afraid. Newer versions of the package are smarter than that.

I suggest starting with the following.
```
pip install --upgrade pip setuptools
pip install --upgrade cmake scikit-build
```

(Have a look at https://manual.gromacs.org/2020-current/gmxapi/userguide/install.html#set-up-a-python-virtual-environment )

**Comment by sperezconesa** [comment]
I have done that and now I get this instead:
```bash
Collecting gmxapi==0.1.0.1
  Using cached gmxapi-0.1.0.1.tar.gz (284 kB)
    ERROR: Command errored out with exit status 1:
     command: /nethome/sperez/bin/anaconda3/envs/string_method3/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_5_vaxlp/gmxapi_76ae43f7e9eb4ad7800b57132e537297/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_5_vaxlp/gmxapi_76ae43f7e9eb4ad7800b57132e537297/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-15himu6e
         cwd: /tmp/pip-install-_5_vaxlp/gmxapi_76ae43f7e9eb4ad7800b57132e537297/
    Complete output (37 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-_5_vaxlp/gmxapi_76ae43f7e9eb4ad7800b57132e537297/setup.py", line 116, in <module>
        raise GmxapiInstallError('Could not configure for GROMACS installation. Provide GMXTOOLCHAINDIR.')
    __main__.GmxapiInstallError: Could not configure for GROMACS installation. Provide GMXTOOLCHAINDIR.

    The `gmxapi` package requires an existing GROMACS installation, version 2020 or higher.
    To specify the GROMACS installation to use, provide a GMXTOOLCHAINDIR
    environment variable when running setup.py or `pip`.

    Example:
        GMXTOOLCHAINDIR=/path/to/gromacs/share/cmake/gromacs pip install gmxapi

    If you have multiple builds of GROMACS, distinguished by a suffix `$SUFFIX`, the
    tool chain directory will use that suffix.

    Example:
        GMXTOOLCHAINDIR=/path/to/gromacs/share/cmake/gromacs$SUFFIX pip install gmxapi

    In the example, `gmxapi` is downloaded automatically from pypi.org. You can
    replace `gmxapi` with a local directory or archive file to build from a source
    distribution.

    setup.py will use the location of GMXTOOLCHAINDIR to locate the
    gmxapi library configured during GROMACS installation. Alternatively, if
    gmxapi_DIR is provided, or if GMXRC has been "sourced", the toolchain file
    location may be deduced. Note, though, that if multiple GROMACS installations
    exist in the same location (with different suffixes) only the first one will be
    used when guessing a toolchain, because setup.py does not know which corresponds
    to the gmxapi support library.

    If specifying GMXTOOLCHAINDIR and gmxapi_DIR, the tool chain directory must be
    located within a subdirectory of gmxapi_DIR.

    Refer to project web site for complete documentation.


    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/6e/c7/ad26d9706474e43ef1a7589397cc2080cebd9deca48efdaaee956c43d8b7/gmxapi-0.1.0.1.tar.gz#sha256=3371075975117a32ffe44e8972a4a9330da416f0054e00ee587cdffb217497a0 (from https://pypi.org/simple/gmxapi/) (requires-python:>=3.5, <3.9). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement gmxapi==0.1.0.1
ERROR: No matching distribution found for gmxapi==0.1.0.1
```

**Comment by sperezconesa** [comment]
Awesome! All those things together worked. Thanks a lot.

**Comment by eirrgang** [comment]
Great! Thanks!
